# Multi-Asset CTA Strategy V2 — Transition Strategy

## 01 — Universe and Data Engine

This notebook establishes the initial V2 cross-asset research universe and data layer.

### Included
- Equity indices
- FX
- Commodities
- Bonds and rates
- Bitcoin

### Excluded for now
- Individual stocks
- Other digital assets

All outputs from this notebook are written to:

`/content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/`

In [ ]:
# ============================================================
# 0) INSTALL AND IMPORT
# ============================================================

import sys
import subprocess
import importlib.util

for package in ["yfinance", "pyarrow"]:
    if importlib.util.find_spec(package) is None:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-q", package]
        )

from pathlib import Path
import json
import warnings

import numpy as np
import pandas as pd
import yfinance as yf

warnings.filterwarnings("ignore")

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 180)

print("V2.01 environment ready.")

V2.01 environment ready.

In [ ]:
# ============================================================
# 1) GOOGLE DRIVE AND V2.01 DIRECTORIES
# ============================================================

from google.colab import drive

drive.mount("/content/drive")

PROJECT_PARENT = Path(
    "/content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2"
)

OUTPUT_ROOT = PROJECT_PARENT / "v2.01"

DIRS = {
    "root": OUTPUT_ROOT,
    "data_raw": OUTPUT_ROOT / "data" / "raw",
    "data_processed": OUTPUT_ROOT / "data" / "processed",
    "data_cache": OUTPUT_ROOT / "data" / "cache",
    "results": OUTPUT_ROOT / "results",
    "figures": OUTPUT_ROOT / "figures",
    "manifests": OUTPUT_ROOT / "manifests",
    "config": OUTPUT_ROOT / "config",
}

for path in DIRS.values():
    path.mkdir(parents=True, exist_ok=True)

print("Project parent:", PROJECT_PARENT)
print("V2.01 output root:", OUTPUT_ROOT)

for key, path in DIRS.items():
    print(f"{key:>16}: {path}")

Mounted at /content/drive
Project parent: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2
V2.01 output root: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01
            root: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01
        data_raw: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/data/raw
  data_processed: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/data/processed
      data_cache: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/data/cache
         results: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/results
         figures: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/figures
       manifests: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/manifests
          config: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/config

## Research-date policy

The default research sample ends on **31 December 2025**.

Because V2 is being designed during 2026, 2026 observations should not be described as a pristine final holdout. They can later be used deliberately as a shadow validation period.

A genuinely untouched final holdout should be designated prospectively before the finished strategy is frozen.

In [ ]:
# ============================================================
# 2) RESEARCH DATES AND CONFIGURATION
# ============================================================

DATA_START = "1990-01-01"
DIGITAL_ASSETS_START = "2017-01-01"
RESEARCH_END = "2025-12-31"
ALLOW_POST_2025 = False

# yfinance end date is exclusive.
DOWNLOAD_END = None if ALLOW_POST_2025 else "2026-01-01"

CONFIG = {
    "notebook": "01 - V2 Universe and Data Engine",
    "output_root": str(OUTPUT_ROOT),
    "data_start": DATA_START,
    "digital_assets_start": DIGITAL_ASSETS_START,
    "research_end": RESEARCH_END,
    "allow_post_2025": ALLOW_POST_2025,
}

config_path = DIRS["config"] / "v2_01_config.json"

with config_path.open("w", encoding="utf-8") as f:
    json.dump(CONFIG, f, indent=2)

print(json.dumps(CONFIG, indent=2))

{
  "notebook": "01 - V2 Universe and Data Engine",
  "output_root": "/content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01",
  "data_start": "1990-01-01",
  "digital_assets_start": "2017-01-01",
  "research_end": "2025-12-31",
  "allow_post_2025": false
}

## Economic asset universe

The universe is defined by the underlying economic market rather than by any broker-specific naming convention.

Each market has:

- candidate signal proxies;
- candidate prototype P&L proxies;
- notes where the initial data source is incomplete or economically imperfect.

Unavailable markets remain in the manifest for later data-source expansion.

In [ ]:
# ============================================================
# 3) MASTER ECONOMIC ASSET UNIVERSE
# ============================================================

rows = []


def add_market(
    category,
    market,
    enabled=True,
    signal_candidates="",
    pnl_candidates="",
    notes="",
    universe_start="",
):
    rows.append(
        {
            "category": category,
            "market": market,
            "enabled": bool(enabled),
            "signal_candidates": signal_candidates,
            "pnl_candidates": pnl_candidates,
            "notes": notes,
            "universe_start": universe_start,
        }
    )


# ------------------------------------------------------------
# EQUITY INDICES
# ------------------------------------------------------------

add_market("INDICES", "S&P 500", True, "^GSPC;SPY", "SPY",
           "Price index for signal; adjusted ETF is a prototype dividend-aware P&L proxy.")
add_market("INDICES", "Nasdaq 100", True, "^NDX;QQQ", "QQQ",
           "Price index for signal; adjusted ETF for prototype P&L.")
add_market("INDICES", "DAX", True, "^GDAXI", "EXS1.DE;EWG",
           "Verify final total-return convention.")
add_market("INDICES", "Nikkei 225", True, "^N225", "1321.T;EWJ",
           "ETF is a prototype economic-return proxy.")
add_market("INDICES", "FTSE 100", True, "^FTSE", "ISF.L;EWU", "")
add_market("INDICES", "Russell 2000", True, "^RUT;IWM", "IWM", "")
add_market("INDICES", "CAC 40", True, "^FCHI", "CAC.PA;EWQ", "")
add_market("INDICES", "Hang Seng", True, "^HSI", "2800.HK;EWH", "")
add_market("INDICES", "VIX", True, "^VIX", "",
           "State variable rather than an initial directional portfolio market.")
add_market("INDICES", "S&P/ASX 200", True, "^AXJO", "IOZ.AX;EWA", "")
add_market("INDICES", "IBEX 35", True, "^IBEX", "EWP",
           "Country ETF is not an exact index replication.")
add_market("INDICES", "Swiss Market Index", True, "^SSMI", "EWL", "")
add_market("INDICES", "AEX", True, "^AEX", "IAEX.AS;EWN", "")
add_market("INDICES", "Hang Seng TECH", True, "^HSTECH;3033.HK", "3033.HK",
           "Historical depth must be checked.")
add_market("INDICES", "OMX Stockholm 30", True, "^OMX", "EWD",
           "Proxy mapping must be validated.")
add_market("INDICES", "South Africa 40", True, "^J203.JO;STX40.JO", "EZA",
           "Index availability may be limited.")
add_market("INDICES", "EURO STOXX Volatility", False, "^V2TX", "",
           "Retained in manifest; prototype source may be unavailable.")
add_market("INDICES", "Hang Seng China Enterprises", True, "^HSCE;2828.HK", "2828.HK;FXI", "")
add_market("INDICES", "Straits Times Index", True, "^STI", "ES3.SI;EWS", "")


# ------------------------------------------------------------
# FX
# ------------------------------------------------------------

fx_markets = [
    ("GBP/USD", "GBPUSD=X"),
    ("EUR/USD", "EURUSD=X"),
    ("USD/JPY", "JPY=X"),
    ("AUD/USD", "AUDUSD=X"),
    ("USD/CAD", "CAD=X"),
    ("EUR/GBP", "EURGBP=X"),
    ("USD/CHF", "CHF=X"),
    ("EUR/JPY", "EURJPY=X"),
    ("EUR/CHF", "EURCHF=X"),
    ("US Dollar Index", "DX-Y.NYB"),
]

for market, proxy in fx_markets:
    add_market(
        "FX",
        market,
        True,
        proxy,
        proxy,
        "Spot prototype excludes interest-rate carry.",
    )



# ------------------------------------------------------------
# DIGITAL ASSETS
# ------------------------------------------------------------

add_market(
    "DIGITAL_ASSETS",
    "BTC-USD",
    True,
    "BTC-USD",
    "BTC-USD",
    (
        "Digital assets enter the V2 universe only from 2017-01-01. "
        "Book 02 applies the full conventional-trend warm-up before BTC "
        "can contribute formal transition events. Kept as a separate asset "
        "class so results can be reported with and without digital assets."
    ),
    DIGITAL_ASSETS_START,
)


# ------------------------------------------------------------
# COMMODITIES
# ------------------------------------------------------------

commodity_markets = [
    ("WTI Crude Oil", "CL=F"),
    ("Brent Crude Oil", "BZ=F"),
    ("Natural Gas", "NG=F"),
    ("RBOB Gasoline", "RB=F"),
    ("Gold", "GC=F"),
    ("Silver", "SI=F"),
    ("Platinum", "PL=F"),
    ("Copper", "HG=F"),
    ("Aluminium", "ALI=F"),
    ("Zinc", ""),
    ("Lead", ""),
    ("Iron Ore", ""),
    ("Nickel", ""),
    ("Cocoa", "CC=F"),
    ("Coffee", "KC=F"),
    ("Sugar No. 11", "SB=F"),
    ("Corn", "ZC=F"),
    ("Soybeans", "ZS=F"),
    ("Cotton", "CT=F"),
    ("Soybean Oil", "ZL=F"),
    ("Live Cattle", "LE=F"),
]

for market, proxy in commodity_markets:
    if proxy:
        note = (
            "Prototype continuous futures series; "
            "roll and collateral economics require later treatment."
        )
    else:
        note = (
            "No dependable prototype proxy assigned yet; "
            "retain for later data-source expansion."
        )

    add_market(
        "COMMODITIES",
        market,
        bool(proxy),
        proxy,
        proxy,
        note,
    )


# ------------------------------------------------------------
# BONDS AND RATES
# ------------------------------------------------------------

rates_markets = [
    ("UK 10Y Gilt / Yield", "", "",
     "Needs dedicated source; yields and bond-price returns must not be mixed."),
    ("US Ultra Treasury Bond", "UB=F", "UB=F", ""),
    ("US 30Y Treasury Bond", "ZB=F", "ZB=F", ""),
    ("German Bund", "FGBL=F", "",
     "Prototype availability uncertain; later institutional source preferred."),
    ("Euro-Buxl", "", "", "Dedicated futures source needed."),
    ("US 10Y Treasury Note", "ZN=F", "ZN=F", ""),
    ("Japanese Government Bond", "", "", "Dedicated futures source needed."),
    ("US 5Y Treasury Note", "ZF=F", "ZF=F", ""),
    ("Italian BTP", "", "", "Dedicated futures source needed."),
    ("US 2Y Treasury Note", "ZT=F", "ZT=F", ""),
    ("French OAT", "", "", "Dedicated futures source needed."),
    ("German Bobl", "", "", "Dedicated futures source needed."),
    ("Italian Short-Term BTP", "", "", "Dedicated futures source needed."),
    ("German Schatz", "", "", "Dedicated futures source needed."),
    ("SONIA 3M", "", "", "Dedicated futures source needed."),
    ("Sterling Short-Rate Future", "", "", "Dedicated futures source needed."),
    ("Euribor / ICE Rate Future", "", "", "Dedicated futures source needed."),
    ("30-Day Fed Funds", "ZQ=F", "ZQ=F",
     "Economic-return convention requires validation."),
    ("20+ Year Treasury ETF", "TLT", "TLT",
     "Adjusted ETF useful as a dividend-aware prototype."),
]

for market, signal_proxy, pnl_proxy, note in rates_markets:
    add_market(
        "BONDS_RATES",
        market,
        bool(signal_proxy),
        signal_proxy,
        pnl_proxy,
        note,
    )


universe = pd.DataFrame(rows)

print("Universe created.")
print()

display(
    universe.groupby("category")
    .size()
    .rename("n_markets")
    .to_frame()
)

display(universe)

Universe created.

                n_markets
category
BONDS_RATES            19
COMMODITIES            21
DIGITAL_ASSETS          1
FX                     10
INDICES                19

          category                       market  enabled  signal_candidates pnl_candidates                                              notes universe_start
0          INDICES                      S&P 500     True          ^GSPC;SPY            SPY  Price index for signal; adjusted ETF is a prot...
1          INDICES                   Nasdaq 100     True           ^NDX;QQQ            QQQ  Price index for signal; adjusted ETF for proto...
2          INDICES                          DAX     True             ^GDAXI    EXS1.DE;EWG              Verify final total-return convention.
3          INDICES                   Nikkei 225     True              ^N225     1321.T;EWJ          ETF is a prototype economic-return proxy.
4          INDICES                     FTSE 100     True              ^FTSE      ISF.L;EWU
5          INDICES                 Russell 2000     True           ^RUT;IWM            IWM
6          INDICES                       CAC 40     True              ^FCHI     CAC.PA;EWQ
7          INDICES                    Hang Seng     True               ^HSI    2800.HK;EWH
8          INDICES                          VIX     True               ^VIX                 State variable rather than an initial directio...
9          INDICES                  S&P/ASX 200     True              ^AXJO     IOZ.AX;EWA
10         INDICES                      IBEX 35     True              ^IBEX            EWP     Country ETF is not an exact index replication.
11         INDICES           Swiss Market Index     True              ^SSMI            EWL
12         INDICES                          AEX     True               ^AEX    IAEX.AS;EWN
13         INDICES               Hang Seng TECH     True    ^HSTECH;3033.HK        3033.HK                  Historical depth must be checked.
14         INDICES             OMX Stockholm 30     True               ^OMX            EWD                   Proxy mapping must be validated.
15         INDICES              South Africa 40     True  ^J203.JO;STX40.JO            EZA                 Index availability may be limited.
16         INDICES        EURO STOXX Volatility    False              ^V2TX                 Retained in manifest; prototype source may be ...
17         INDICES  Hang Seng China Enterprises     True      ^HSCE;2828.HK    2828.HK;FXI
18         INDICES          Straits Times Index     True               ^STI     ES3.SI;EWS
19              FX                      GBP/USD     True           GBPUSD=X       GBPUSD=X       Spot prototype excludes interest-rate carry.
20              FX                      EUR/USD     True           EURUSD=X       EURUSD=X       Spot prototype excludes interest-rate carry.
21              FX                      USD/JPY     True              JPY=X          JPY=X       Spot prototype excludes interest-rate carry.
22              FX                      AUD/USD     True           AUDUSD=X       AUDUSD=X       Spot prototype excludes interest-rate carry.
23              FX                      USD/CAD     True              CAD=X          CAD=X       Spot prototype excludes interest-rate carry.
24              FX                      EUR/GBP     True           EURGBP=X       EURGBP=X       Spot prototype excludes interest-rate carry.
25              FX                      USD/CHF     True              CHF=X          CHF=X       Spot prototype excludes interest-rate carry.
26              FX                      EUR/JPY     True           EURJPY=X       EURJPY=X       Spot prototype excludes interest-rate carry.
27              FX                      EUR/CHF     True           EURCHF=X       EURCHF=X       Spot prototype excludes interest-rate carry.
28              FX              US Dollar Index     True           DX-Y.NYB       DX-Y.NYB       Spot prototype excludes interest-rate carry.
29  DIGITAL_ASSETS                      BTC-USD     True            BTC-USD        BTC-USD  Digital assets enter the V2 universe only from...     2017-01-01
30     COMMODITIES                WTI Crude Oil     True               CL=F           CL=F  Prototype continuous futures series; roll and ...
31     COMMODITIES              Brent Crude Oil     True               BZ=F           BZ=F  Prototype continuous futures series; roll and ...
32     COMMODITIES                  Natural Gas     True               NG=F           NG=F  Prototype continuous futures series; roll and ...
33     COMMODITIES                RBOB Gasoline     True               RB=F           RB=F  Prototype continuous futures series; roll and ...
34     COMMODITIES                         Gold     True               GC=F           GC=F  Prototype continuous futures series; roll and ...
35     COMMODITIES                       Silver     True               SI=F           SI=F  Prototype continuous futures series; roll and ...
36     COMMODITIES                     Platinum     True               PL=F           PL=F  Prototype continuous futures series; roll and ...
37     COMMODITIES                       Copper     True               HG=F           HG=F  Prototype continuous futures series; roll and ...
38     COMMODITIES                    Aluminium     True              ALI=F          ALI=F  Prototype continuous futures series; roll and ...
39     COMMODITIES                         Zinc    False                                    No dependable prototype proxy assigned yet; re...
40     COMMODITIES                         Lead    False                                    No dependable prototype proxy assigned yet; re...
41     COMMODITIES                     Iron Ore    False                                    No dependable prototype proxy assigned yet; re...
42     COMMODITIES                       Nickel    False                                    No dependable prototype proxy assigned yet; re...
43     COMMODITIES                        Cocoa     True               CC=F           CC=F  Prototype continuous futures series; roll and ...
44     COMMODITIES                       Coffee     True               KC=F           KC=F  Prototype continuous futures series; roll and ...
45     COMMODITIES                 Sugar No. 11     True               SB=F           SB=F  Prototype continuous futures series; roll and ...
46     COMMODITIES                         Corn     True               ZC=F           ZC=F  Prototype continuous futures series; roll and ...
47     COMMODITIES                     Soybeans     True               ZS=F           ZS=F  Prototype continuous futures series; roll and ...
48     COMMODITIES                       Cotton     True               CT=F           CT=F  Prototype continuous futures series; roll and ...
49     COMMODITIES                  Soybean Oil     True               ZL=F           ZL=F  Prototype continuous futures series; roll and ...
50     COMMODITIES                  Live Cattle     True               LE=F           LE=F  Prototype continuous futures series; roll and ...
51     BONDS_RATES          UK 10Y Gilt / Yield    False                                    Needs dedicated source; yields and bond-price ...
52     BONDS_RATES       US Ultra Treasury Bond     True               UB=F           UB=F
53     BONDS_RATES         US 30Y Treasury Bond     True               ZB=F           ZB=F
54     BONDS_RATES                  German Bund     True             FGBL=F                 Prototype availability uncertain; later instit...
55     BONDS_RATES                    Euro-Buxl    False                                                     Dedicated futures source needed.
56     BONDS_RATES         US 10Y Treasury Note     True               ZN=F           ZN=F
57     BONDS_RATES     Japanese Government Bond    False                                                     Dedicated futures source needed.
58     BONDS_RATES          US 5Y Treasury Note     True               ZF=F           ZF=F
59     BONDS_RATES                  Italian BTP    False                                                     Dedicated futures source needed.
60     BONDS_RATES          US 2Y Treasury Note     True               ZT=F           ZT=F
61     BONDS_RATES                   French OAT    False                                                     Dedicated futures source needed.
62     BONDS_RATES                  German Bobl    False                                                     Dedicated futures source needed.
63     BONDS_RATES       Italian Short-Term BTP    False                                                     Dedicated futures source needed.
64     BONDS_RATES                German Schatz    False                                                     Dedicated futures source needed.
65     BONDS_RATES                     SONIA 3M    False                                                     Dedicated futures source needed.
66     BONDS_RATES   Sterling Short-Rate Future    False                                                     Dedicated futures source needed.
67     BONDS_RATES    Euribor / ICE Rate Future    False                                                     Dedicated futures source needed.
68     BONDS_RATES             30-Day Fed Funds     True               ZQ=F           ZQ=F    Economic-return convention requires validation.
69     BONDS_RATES        20+ Year Treasury ETF     True                TLT            TLT  Adjusted ETF useful as a dividend-aware protot...

In [ ]:
# ============================================================
# 4) SCOPE CHECK AND MANIFEST
# ============================================================

allowed_categories = {
    "INDICES",
    "FX",
    "COMMODITIES",
    "BONDS_RATES",
    "DIGITAL_ASSETS",
}

actual_categories = set(universe["category"])
unexpected_categories = actual_categories.difference(allowed_categories)

if unexpected_categories:
    raise ValueError(
        "Unexpected categories in V2.01 universe: "
        + str(sorted(unexpected_categories))
    )

if "STOCKS" in actual_categories:
    raise ValueError("Individual stocks must not be present in V2.01.")

manifest_path = DIRS["manifests"] / "v2_master_universe.csv"
universe.to_csv(manifest_path, index=False)

print("Scope check passed.")
print("Included: equity indices, FX, commodities, bonds and rates, digital assets.")
print("Total economic markets:", len(universe))
print("Enabled prototype markets:", int(universe["enabled"].sum()))
print("Awaiting a better data source:", int((~universe["enabled"]).sum()))
print("Manifest:", manifest_path)

Scope check passed.
Included: equity indices, FX, commodities, bonds and rates, digital assets.
Total economic markets: 70
Enabled prototype markets: 54
Awaiting a better data source: 16
Manifest: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/manifests/v2_master_universe.csv

## Signal prices versus prototype P&L prices

These concepts are deliberately kept separate.

**Signal series** are used later for trend, divergence, SuperbCommand and HMM features.

**P&L series** are used to estimate the economic return from holding a position.

They can differ because dividends, coupons, FX carry, futures roll and collateral returns are not always contained in quoted price histories.

In [ ]:
# ============================================================
# 5) DOWNLOAD HELPERS
# ============================================================

def parse_candidates(value):
    if value is None:
        return []

    if isinstance(value, float) and np.isnan(value):
        return []

    return [
        symbol.strip()
        for symbol in str(value).split(";")
        if symbol.strip()
    ]


def download_one(symbol, start=DATA_START, end=DOWNLOAD_END):
    if not symbol:
        return None

    try:
        data = yf.download(
            symbol,
            start=start,
            end=end,
            auto_adjust=False,
            progress=False,
            actions=True,
            threads=False,
        )

        if data is None or data.empty:
            return None

        if isinstance(data.columns, pd.MultiIndex):
            data.columns = [column[0] for column in data.columns]

        data.index = pd.to_datetime(data.index)

        if data.index.tz is not None:
            data.index = data.index.tz_localize(None)

        data = data[~data.index.duplicated(keep="last")]
        data = data.sort_index()

        return data

    except Exception as exc:
        print(f"Download failed for {symbol}: {exc}")
        return None


def choose_first_available(candidates, min_obs=250):
    diagnostics = []

    for symbol in candidates:
        data = download_one(symbol)

        if data is None:
            observations = 0
        else:
            observations = len(data.dropna(how="all"))

        diagnostics.append((symbol, observations))

        if data is not None and observations >= min_obs:
            return symbol, data, diagnostics

    return None, None, diagnostics


def extract_signal_price(data):
    if data is None:
        return None

    if "Close" not in data.columns:
        return None

    return data["Close"].astype(float)


def extract_pnl_price(data):
    if data is None:
        return None

    if "Adj Close" in data.columns:
        adjusted = data["Adj Close"]

        if adjusted.notna().sum() > 0:
            return adjusted.astype(float)

    if "Close" in data.columns:
        return data["Close"].astype(float)

    return None


print("Download helpers ready.")

Download helpers ready.

In [ ]:
# ============================================================
# 6) PROBE PROTOTYPE DATA COVERAGE
# ============================================================

RUN_COVERAGE_PROBE = True

coverage_rows = []
raw_cache = {}

if RUN_COVERAGE_PROBE:
    probe_universe = universe.loc[universe["enabled"]].copy()

    for _, row in probe_universe.iterrows():
        signal_candidates = parse_candidates(row["signal_candidates"])
        pnl_candidates = parse_candidates(row["pnl_candidates"])

        signal_symbol, signal_data, signal_diagnostics = (
            choose_first_available(signal_candidates)
        )

        pnl_symbol, pnl_data, pnl_diagnostics = (
            choose_first_available(pnl_candidates)
        )

        if signal_symbol is not None and signal_data is not None:
            raw_cache[("signal", row["market"])] = signal_data

        if pnl_symbol is not None and pnl_data is not None:
            raw_cache[("pnl", row["market"])] = pnl_data

        coverage_rows.append(
            {
                "category": row["category"],
                "market": row["market"],
                "universe_start": row.get("universe_start", ""),
                "signal_symbol": signal_symbol,
                "signal_obs": 0 if signal_data is None else len(signal_data),
                "signal_start": (
                    None
                    if signal_data is None
                    else signal_data.index.min().date()
                ),
                "signal_end": (
                    None
                    if signal_data is None
                    else signal_data.index.max().date()
                ),
                "pnl_symbol": pnl_symbol,
                "pnl_obs": 0 if pnl_data is None else len(pnl_data),
                "pnl_start": (
                    None
                    if pnl_data is None
                    else pnl_data.index.min().date()
                ),
                "pnl_end": (
                    None
                    if pnl_data is None
                    else pnl_data.index.max().date()
                ),
                "signal_probe": str(signal_diagnostics),
                "pnl_probe": str(pnl_diagnostics),
            }
        )

coverage = pd.DataFrame(coverage_rows)

if coverage.empty:
    print("Coverage probe produced no rows.")

else:
    coverage["signal_ok"] = coverage["signal_symbol"].notna()
    coverage["pnl_ok"] = coverage["pnl_symbol"].notna()

    coverage = coverage.sort_values(
        ["signal_ok", "category", "market"],
        ascending=[True, True, True],
    )

    display(coverage)

    print(
        "Signal coverage:",
        f"{coverage['signal_ok'].mean():.1%}",
    )

    print(
        "P&L coverage:",
        f"{coverage['pnl_ok'].mean():.1%}",
    )

    coverage_path = (
        DIRS["manifests"] / "v2_01_prototype_coverage.csv"
    )

    coverage.to_csv(coverage_path, index=False)

    print("Coverage report:", coverage_path)

ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: ^HSTECH"}}}
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['^HSTECH']: YFTzMissingError('possibly delisted; no timezone found')
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FGBL=F"}}}
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['FGBL=F']: YFTzMissingError('possibly delisted; no timezone found')

,category,market,universe_start,signal_symbol,signal_obs,signal_start,signal_end,pnl_symbol,pnl_obs,pnl_start,pnl_end,signal_probe,pnl_probe,signal_ok,pnl_ok
48,BONDS_RATES,German Bund,,None,0,None,None,None,0,None,None,"[('FGBL=F', 0)]",[],False,False
53,BONDS_RATES,20+ Year Treasury ETF,,TLT,5895,2002-07-30,2025-12-31,TLT,5895,2002-07-30,2025-12-31,"[('TLT', 5895)]","[('TLT', 5895)]",True,True
52,BONDS_RATES,30-Day Fed Funds,,ZQ=F,6344,2000-09-01,2025-12-31,ZQ=F,6344,2000-09-01,2025-12-31,"[('ZQ=F', 6344)]","[('ZQ=F', 6344)]",True,True
49,BONDS_RATES,US 10Y Treasury Note,,ZN=F,6348,2000-09-21,2025-12-31,ZN=F,6348,2000-09-21,2025-12-31,"[('ZN=F', 6348)]","[('ZN=F', 6348)]",True,True
51,BONDS_RATES,US 2Y Treasury Note,,ZT=F,6414,2000-06-02,2025-12-31,ZT=F,6414,2000-06-02,2025-12-31,"[('ZT=F', 6414)]","[('ZT=F', 6414)]",True,True
47,BONDS_RATES,US 30Y Treasury Bond,,ZB=F,6354,2000-09-21,2025-12-31,ZB=F,6354,2000-09-21,2025-12-31,"[('ZB=F', 6354)]","[('ZB=F', 6354)]",True,True
50,BONDS_RATES,US 5Y Treasury Note,,ZF=F,6360,2000-09-21,2025-12-31,ZF=F,6360,2000-09-21,2025-12-31,"[('ZF=F', 6360)]","[('ZF=F', 6360)]",True,True
46,BONDS_RATES,US Ultra Treasury Bond,,UB=F,4018,2010-01-11,2025-12-31,UB=F,4018,2010-01-11,2025-12-31,"[('UB=F', 4018)]","[('UB=F', 4018)]",True,True
37,COMMODITIES,Aluminium,,ALI=F,2896,2014-05-06,2025-12-31,ALI=F,2896,2014-05-06,2025-12-31,"[('ALI=F', 2896)]","[('ALI=F', 2896)]",True,True
30,COMMODITIES,Brent Crude Oil,,BZ=F,4585,2007-07-30,2025-12-31,BZ=F,4585,2007-07-30,2025-12-31,"[('BZ=F', 4585)]","[('BZ=F', 4585)]",True,True
38,COMMODITIES,Cocoa,,CC=F,6520,2000-01-03,2025-12-31,CC=F,6520,2000-01-03,2025-12-31,"[('CC=F', 6520)]","[('CC=F', 6520)]",True,True
39,COMMODITIES,Coffee,,KC=F,6518,2000-01-03,2025-12-31,KC=F,6518,2000-01-03,2025-12-31,"[('KC=F', 6518)]","[('KC=F', 6518)]",True,True
36,COMMODITIES,Copper,,HG=F,6363,2000-08-30,2025-12-31,HG=F,6363,2000-08-30,2025-12-31,"[('HG=F', 6363)]","[('HG=F', 6363)]",True,True
41,COMMODITIES,Corn,,ZC=F,6370,2000-07-17,2025-12-31,ZC=F,6370,2000-07-17,2025-12-31,"[('ZC=F', 6370)]","[('ZC=F', 6370)]",True,True
43,COMMODITIES,Cotton,,CT=F,6520,2000-01-03,2025-12-31,CT=F,6520,2000-01-03,2025-12-31,"[('CT=F', 6520)]","[('CT=F', 6520)]",True,True
33,COMMODITIES,Gold,,GC=F,6358,2000-08-30,2025-12-31,GC=F,6358,2000-08-30,2025-12-31,"[('GC=F', 6358)]","[('GC=F', 6358)]",True,True
45,COMMODITIES,Live Cattle,,LE=F,6225,2001-03-01,2025-12-31,LE=F,6225,2001-03-01,2025-12-31,"[('LE=F', 6225)]","[('LE=F', 6225)]",True,True
31,COMMODITIES,Natural Gas,,NG=F,6364,2000-08-30,2025-12-31,NG=F,6364,2000-08-30,2025-12-31,"[('NG=F', 6364)]","[('NG=F', 6364)]",True,True
35,COMMODITIES,Platinum,,PL=F,6386,1997-10-29,2025-12-31,PL=F,6386,1997-10-29,2025-12-31,"[('PL=F', 6386)]","[('PL=F', 6386)]",True,True
32,COMMODITIES,RBOB Gasoline,,RB=F,6322,2000-11-01,2025-12-31,RB=F,6322,2000-11-01,2025-12-31,"[('RB=F', 6322)]","[('RB=F', 6322)]",True,True
34,COMMODITIES,Silver,,SI=F,6360,2000-08-30,2025-12-31,SI=F,6360,2000-08-30,2025-12-31,"[('SI=F', 6360)]","[('SI=F', 6360)]",True,True
44,COMMODITIES,Soybean Oil,,ZL=F,6411,2000-03-15,2025-12-31,ZL=F,6411,2000-03-15,2025-12-31,"[('ZL=F', 6411)]","[('ZL=F', 6411)]",True,True
42,COMMODITIES,Soybeans,,ZS=F,6362,2000-09-15,2025-12-31,ZS=F,6362,2000-09-15,2025-12-31,"[('ZS=F', 6362)]","[('ZS=F', 6362)]",True,True
40,COMMODITIES,Sugar No. 11,,SB=F,6481,2000-03-01,2025-12-31,SB=F,6481,2000-03-01,2025-12-31,"[('SB=F', 6481)]","[('SB=F', 6481)]",True,True
29,COMMODITIES,WTI Crude Oil,,CL=F,6367,2000-08-23,2025-12-31,CL=F,6367,2000-08-23,2025-12-31,"[('CL=F', 6367)]","[('CL=F', 6367)]",True,True
28,DIGITAL_ASSETS,BTC-USD,2017-01-01,BTC-USD,4124,2014-09-17,2025-12-31,BTC-USD,4124,2014-09-17,2025-12-31,"[('BTC-USD', 4124)]","[('BTC-USD', 4124)]",True,True
21,FX,AUD/USD,,AUDUSD=X,5106,2006-05-16,2025-12-31,AUDUSD=X,5106,2006-05-16,2025-12-31,"[('AUDUSD=X', 5106)]","[('AUDUSD=X', 5106)]",True,True
26,FX,EUR/CHF,,EURCHF=X,5953,2003-01-23,2025-12-31,EURCHF=X,5953,2003-01-23,2025-12-31,"[('EURCHF=X', 5953)]","[('EURCHF=X', 5953)]",True,True
23,FX,EUR/GBP,,EURGBP=X,7030,1999-01-04,2025-12-31,EURGBP=X,7030,1999-01-04,2025-12-31,"[('EURGBP=X', 7030)]","[('EURGBP=X', 7030)]",True,True
25,FX,EUR/JPY,,EURJPY=X,5955,2003-01-23,2025-12-31,EURJPY=X,5955,2003-01-23,2025-12-31,"[('EURJPY=X', 5955)]","[('EURJPY=X', 5955)]",True,True
19,FX,EUR/USD,,EURUSD=X,5730,2003-12-01,2025-12-31,EURUSD=X,5730,2003-12-01,2025-12-31,"[('EURUSD=X', 5730)]","[('EURUSD=X', 5730)]",True,True
18,FX,GBP/USD,,GBPUSD=X,5742,2003-12-01,2025-12-31,GBPUSD=X,5742,2003-12-01,2025-12-31,"[('GBPUSD=X', 5742)]","[('GBPUSD=X', 5742)]",True,True
27,FX,US Dollar Index,,DX-Y.NYB,9176,1990-01-01,2025-12-31,DX-Y.NYB,9176,1990-01-01,2025-12-31,"[('DX-Y.NYB', 9176)]","[('DX-Y.NYB', 9176)]",True,True
22,FX,USD/CAD,,CAD=X,5798,2003-09-17,2025-12-31,CAD=X,5798,2003-09-17,2025-12-31,"[('CAD=X', 5798)]","[('CAD=X', 5798)]",True,True
24,FX,USD/CHF,,CHF=X,5796,2003-09-17,2025-12-31,CHF=X,5796,2003-09-17,2025-12-31,"[('CHF=X', 5796)]","[('CHF=X', 5796)]",True,True
20,FX,USD/JPY,,JPY=X,7564,1996-10-30,2025-12-31,JPY=X,7564,1996-10-30,2025-12-31,"[('JPY=X', 7564)]","[('JPY=X', 7564)]",True,True
12,INDICES,AEX,,^AEX,8477,1992-10-12,2025-12-31,IAEX.AS,4606,2008-01-02,2025-12-31,"[('^AEX', 8477)]","[('IAEX.AS', 4606)]",True,True
6,INDICES,CAC 40,,^FCHI,9101,1990-03-01,2025-12-31,CAC.PA,4605,2008-01-02,2025-12-31,"[('^FCHI', 9101)]","[('CAC.PA', 4605)]",True,True
2,INDICES,DAX,,^GDAXI,9107,1990-01-02,2025-12-30,EXS1.DE,4569,2008-01-02,2025-12-30,"[('^GDAXI', 9107)]","[('EXS1.DE', 4569)]",True,True
4,INDICES,FTSE 100,,^FTSE,9093,1990-01-02,2025-12-31,ISF.L,4293,2009-01-02,2025-12-31,"[('^FTSE', 9093)]","[('ISF.L', 4293)]",True,True
7,INDICES,Hang Seng,,^HSI,8885,1990-01-02,2025-12-31,2800.HK,4435,2008-01-02,2025-12-31,"[('^HSI', 8885)]","[('2800.HK', 4435)]",True,True
16,INDICES,Hang Seng China Enterprises,,^HSCE,8008,1993-07-15,2025-12-31,2828.HK,416,2024-04-24,2025-12-31,"[('^HSCE', 8008)]","[('2828.HK', 416)]",True,True
13,INDICES,Hang Seng TECH,,3033.HK,1313,2020-08-27,2025-12-31,3033.HK,1313,2020-08-27,2025-12-31,"[('^HSTECH', 0), ('3033.HK', 1313)]","[('3033.HK', 1313)]",True,True
10,INDICES,IBEX 35,,^IBEX,8228,1993-07-12,2025-12-31,EWP,7497,1996-03-18,2025-12-31,"[('^IBEX', 8228)]","[('EWP', 7497)]",True,True
1,INDICES,Nasdaq 100,,^NDX,9067,1990-01-02,2025-12-31,QQQ,6746,1999-03-10,2025-12-31,"[('^NDX', 9067)]","[('QQQ', 6746)]",True,True
3,INDICES,Nikkei 225,,^N225,8835,1990-01-04,2025-12-30,1321.T,4174,2009-01-05,2025-12-30,"[('^N225', 8835)]","[('1321.T', 4174)]",True,True
14,INDICES,OMX Stockholm 30,,^OMX,4291,2008-11-20,2025-12-30,EWD,7497,1996-03-18,2025-12-31,"[('^OMX', 4291)]","[('EWD', 7497)]",True,True
5,INDICES,Russell 2000,,^RUT,9067,1990-01-02,2025-12-31,IWM,6438,2000-05-26,2025-12-31,"[('^RUT', 9067)]","[('IWM', 6438)]",True,True
0,INDICES,S&P 500,,^GSPC,9067,1990-01-02,2025-12-31,SPY,8288,1993-01-29,2025-12-31,"[('^GSPC', 9067)]","[('SPY', 8288)]",True,True
9,INDICES,S&P/ASX 200,,^AXJO,8369,1992-11-23,2025-12-31,IOZ.AX,3808,2010-12-07,2025-12-31,"[('^AXJO', 8369)]","[('IOZ.AX', 3808)]",True,True
15,INDICES,South Africa 40,,^J203.JO,3492,2012-02-08,2025-12-31,EZA,5762,2003-02-07,2025-12-31,"[('^J203.JO', 3492)]","[('EZA', 5762)]",True,True
17,INDICES,Straits Times Index,,^STI,9002,1990-01-02,2025-12-31,ES3.SI,4515,2008-01-02,2025-12-31,"[('^STI', 9002)]","[('ES3.SI', 4515)]",True,True
11,INDICES,Swiss Market Index,,^SSMI,8824,1990-11-09,2025-12-30,EWL,7497,1996-03-18,2025-12-31,"[('^SSMI', 8824)]","[('EWL', 7497)]",True,True
8,INDICES,VIX,,^VIX,9067,1990-01-02,2025-12-31,None,0,None,None,"[('^VIX', 9067)]",[],True,False

Signal coverage: 98.1%
P&L coverage: 96.3%
Coverage report: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/manifests/v2_01_prototype_coverage.csv

In [ ]:
# ============================================================
# 7) BUILD SIGNAL AND P&L PANELS
# ============================================================

def build_panel(kind):
    if coverage.empty:
        return pd.DataFrame()

    collected = {}

    for _, row in coverage.iterrows():
        symbol = row[f"{kind}_symbol"]

        if pd.isna(symbol):
            continue

        data = raw_cache.get((kind, row["market"]))

        if data is None:
            data = download_one(symbol)

        if data is None:
            continue

        if kind == "signal":
            series = extract_signal_price(data)

        elif kind == "pnl":
            series = extract_pnl_price(data)

        else:
            raise ValueError("kind must be 'signal' or 'pnl'")

        if series is None:
            continue

        series.name = row["market"]
        collected[row["market"]] = series

    if not collected:
        return pd.DataFrame()

    panel = pd.concat(
        list(collected.values()),
        axis=1,
    ).sort_index()

    panel.columns = list(collected.keys())

    return panel


signal_prices = build_panel("signal")
pnl_prices = build_panel("pnl")

print("Signal panel shape:", signal_prices.shape)
print("P&L panel shape:", pnl_prices.shape)

display(signal_prices.tail())

Signal panel shape: (10571, 53)
P&L panel shape: (10571, 52)

,20+ Year Treasury ETF,30-Day Fed Funds,US 10Y Treasury Note,US 2Y Treasury Note,US 30Y Treasury Bond,US 5Y Treasury Note,US Ultra Treasury Bond,Aluminium,Brent Crude Oil,Cocoa,Coffee,Copper,Corn,Cotton,Gold,Live Cattle,Natural Gas,Platinum,RBOB Gasoline,Silver,Soybean Oil,Soybeans,Sugar No. 11,WTI Crude Oil,BTC-USD,AUD/USD,EUR/CHF,EUR/GBP,EUR/JPY,EUR/USD,GBP/USD,US Dollar Index,USD/CAD,USD/CHF,USD/JPY,AEX,CAC 40,DAX,FTSE 100,Hang Seng,Hang Seng China Enterprises,Hang Seng TECH,IBEX 35,Nasdaq 100,Nikkei 225,OMX Stockholm 30,Russell 2000,S&P 500,S&P/ASX 200,South Africa 40,Straits Times Index,Swiss Market Index,VIX
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87802.156250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87835.835938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-29,88.070000,96.277496,112.718750,104.324219,115.87500,109.460938,118.500,2835.50,61.939999,6242.0,352.149994,5.4905,442.25,64.349998,4325.100098,228.899994,4.687,2104.800049,1.7152,69.856003,48.779999,1049.50,15.26,58.080002,87138.140625,0.67141,0.92900,0.87216,184.240005,1.177274,1.349728,98.040001,1.36683,0.78924,156.462997,946.159973,8112.020020,24351.119141,9866.500000,25635.230469,8891.709961,5.37,17195.800781,25525.560547,50526.921875,2863.639893,2519.800049,6905.740234,8725.700195,116047.898438,4633.640137,13240.589844,14.20
2025-12-30,87.860001,96.277496,112.640625,104.359375,115.81250,109.468750,118.375,2899.25,61.919998,6063.0,350.200012,5.7275,440.50,64.320000,4370.100098,231.175003,3.972,2232.300049,1.7210,77.374001,48.930000,1046.25,14.84,57.950001,88430.132812,0.66955,0.92877,0.87140,183.690002,1.177288,1.351099,98.239998,1.36872,0.78870,156.013000,951.270020,8168.149902,24490.410156,9940.700195,25854.599609,8991.019531,5.46,17354.900391,25462.560547,50339.480469,2882.969971,2500.590088,6896.240234,8717.099609,116501.203125,4655.379883,13267.480469,14.33
2025-12-31,87.160004,96.277496,112.437500,104.386719,115.59375,109.343750,118.000,2906.25,60.849998,6065.0,348.750000,5.6300,440.25,64.269997,4325.600098,232.000000,3.686,2034.500000,1.7054,70.134003,48.070000,1030.50,15.01,57.419998,87508.828125,0.66980,0.93006,0.87224,183.720001,1.174729,1.346720,98.279999,1.36947,0.79170,156.412994,951.289978,8149.500000,NaN,9931.400391,25630.539062,8913.679688,5.39,17307.800781,25249.849609,NaN,NaN,2481.909912,6845.500000,8714.299805,115832.296875,4646.209961,NaN,14.95

In [ ]:
# ============================================================
# 8) DATA-QUALITY REPORT
# ============================================================

def build_quality_report(prices):
    report_rows = []

    for market in prices.columns:
        series = prices[market].dropna()

        if series.empty:
            continue

        returns = series.pct_change()

        report_rows.append(
            {
                "market": market,
                "start": series.index.min().date(),
                "end": series.index.max().date(),
                "observations": len(series),
                "missing_pct_full_panel": prices[market].isna().mean(),
                "zero_return_pct": returns.eq(0).mean(),
                "max_abs_daily_return": returns.abs().max(),
                "median_abs_daily_return": returns.abs().median(),
            }
        )

    if not report_rows:
        return pd.DataFrame()

    return (
        pd.DataFrame(report_rows)
        .sort_values("market")
        .reset_index(drop=True)
    )


signal_quality = build_quality_report(signal_prices)

display(signal_quality)

quality_path = DIRS["manifests"] / "v2_01_signal_quality.csv"
signal_quality.to_csv(quality_path, index=False)

print("Quality report:", quality_path)

                         market       start         end  observations  missing_pct_full_panel  zero_return_pct  max_abs_daily_return  median_abs_daily_return
0         20+ Year Treasury ETF  2002-07-30  2025-12-31          5895                0.442342         0.005259              0.075196                 0.005356
1              30-Day Fed Funds  2000-09-01  2025-12-31          6344                0.399868         0.610656              0.010253                 0.000000
2                           AEX  1992-10-12  2025-12-31          8477                0.198089         0.001180              0.107526                 0.006050
3                       AUD/USD  2006-05-16  2025-12-31          5106                0.516980         0.004700              0.094182                 0.004033
4                     Aluminium  2014-05-06  2025-12-31          2896                0.726043         0.165746              0.182022                 0.005874
5                       BTC-USD  2014-09-17  2025-12-31          4124                0.609876         0.000242              0.371695                 0.014427
6               Brent Crude Oil  2007-07-30  2025-12-31          4585                0.566266         0.005453              0.244036                 0.010961
7                        CAC 40  1990-03-01  2025-12-31          9101                0.139060         0.001758              0.122768                 0.006797
8                         Cocoa  2000-01-03  2025-12-31          6520                0.383218         0.014571              0.229388                 0.011261
9                        Coffee  2000-01-03  2025-12-31          6518                0.383407         0.011200              0.180943                 0.012226
10                       Copper  2000-08-30  2025-12-31          6363                0.398070         0.009901              0.222531                 0.008883
11                         Corn  2000-07-17  2025-12-31          6370                0.397408         0.028100              0.235567                 0.009540
12                       Cotton  2000-01-03  2025-12-31          6520                0.383218         0.006595              0.238850                 0.009564
13                          DAX  1990-01-02  2025-12-30          9107                0.138492         0.000000              0.122386                 0.006739
14                      EUR/CHF  2003-01-23  2025-12-31          5953                0.436856         0.013439              0.172052                 0.001628
15                      EUR/GBP  1999-01-04  2025-12-31          7030                0.334973         0.009104              0.116407                 0.002730
16                      EUR/JPY  2003-01-23  2025-12-31          5955                0.436666         0.002015              0.082709                 0.003585
17                      EUR/USD  2003-12-01  2025-12-31          5730                0.457951         0.004363              0.173079                 0.003159
18                     FTSE 100  1990-01-02  2025-12-31          9093                0.139816         0.001540              0.108738                 0.005362
19                      GBP/USD  2003-12-01  2025-12-31          5742                0.456816         0.003831              0.076038                 0.003165
20                         Gold  2000-08-30  2025-12-31          6358                0.398543         0.007078              0.093538                 0.005530
21                    Hang Seng  1990-01-02  2025-12-31          8885                0.159493         0.000563              0.188236                 0.007568
22  Hang Seng China Enterprises  1993-07-15  2025-12-31          8008                0.242456         0.000500              0.182215                 0.010121
23               Hang Seng TECH  2020-08-27  2025-12-31          1313                0.875792         0.012947              0.225939                 0.014108
24                      IBEX 35  1993-07-12  2025-12-31          8228                0.221644         0.001823              0.144350                 0.007047
25                  Live Cattle  2001-03-01  2025-12-31          6225                0.411125         0.034056              0.144849                 0.005246
26                   Nasdaq 100  1990-01-02  2025-12-31          9067                0.142276         0.000662              0.187713                 0.007844
27                  Natural Gas  2000-08-30  2025-12-31          6364                0.397976         0.004557              0.464812                 0.019752
28                   Nikkei 225  1990-01-04  2025-12-30          8835                0.164223         0.000113              0.141503                 0.007667
29             OMX Stockholm 30  2008-11-20  2025-12-30          4291                0.594078         0.000699              0.105710                 0.006297
30                     Platinum  1997-10-29  2025-12-31          6386                0.395894         0.005794              0.434710                 0.008683
31                RBOB Gasoline  2000-11-01  2025-12-31          6322                0.401949         0.001898              0.319789                 0.013575
32                 Russell 2000  1990-01-02  2025-12-31          9067                0.142276         0.001103              0.142720                 0.006592
33                      S&P 500  1990-01-02  2025-12-31          9067                0.142276         0.000551              0.119841                 0.005174
34                  S&P/ASX 200  1992-11-23  2025-12-31          8369                0.208306         0.001912              0.096998                 0.005018
35                       Silver  2000-08-30  2025-12-31          6360                0.398354         0.003774              0.177541                 0.009403
36              South Africa 40  2012-02-08  2025-12-31          3492                0.669662         0.003150            555.012878                 0.005722
37                  Soybean Oil  2000-03-15  2025-12-31          6411                0.393529         0.014350              0.090788                 0.009303
38                     Soybeans  2000-09-15  2025-12-31          6362                0.398165         0.013046              0.225329                 0.008121
39          Straits Times Index  1990-01-02  2025-12-31          9002                0.148425         0.001888              0.137392                 0.005194
40                 Sugar No. 11  2000-03-01  2025-12-31          6481                0.386908         0.016356              0.265504                 0.011596
41           Swiss Market Index  1990-11-09  2025-12-30          8824                0.165263         0.001133              0.113910                 0.005500
42         US 10Y Treasury Note  2000-09-21  2025-12-31          6348                0.399489         0.020794              0.036002                 0.002138
43          US 2Y Treasury Note  2000-06-02  2025-12-31          6414                0.393246         0.055659              0.010215                 0.000426
44         US 30Y Treasury Bond  2000-09-21  2025-12-31          6354                0.398922         0.018728              0.103891                 0.003940
45          US 5Y Treasury Note  2000-09-21  2025-12-31          6360                0.398354         0.022484              0.020901                 0.001308
46              US Dollar Index  1990-01-01  2025-12-31          9176                0.131965         0.018200              0.028944                 0.002774
47       US Ultra Treasury Bond  2010-01-11  2025-12-31          4018                0.619904         0.008960              0.066637                 0.005403
48                      USD/CAD  2003-09-17  2025-12-31          5798                0.451518         0.003105              0.036640                 0.002858
49                      USD/CHF  2003-09-17  2025-12-31          5796                0.451708         0.004141              0.161473                 0.003271
50                      USD/JPY  1996-10-30  2025-12-31          7564                0.284457         0.005685              0.176902                 0.003478
51                          VIX  1990-01-02  2025-12-31          9067                0.142276         0.005515              1.155979                 0.035582
52                WTI Crude Oil  2000-08-23  2025-12-31          6367                0.397692         0.004398              3.059661                 0.013122

Quality report: /content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/manifests/v2_01_signal_quality.csv

In [ ]:
# ============================================================
# 9) SAVE PROCESSED PANELS
# ============================================================

signal_path = (
    DIRS["data_processed"]
    / "v2_01_signal_prices.parquet"
)

pnl_path = (
    DIRS["data_processed"]
    / "v2_01_pnl_prices_prototype.parquet"
)

signal_prices.to_parquet(signal_path)
pnl_prices.to_parquet(pnl_path)

print("Saved signal panel:")
print(signal_path)

print()
print("Saved prototype P&L panel:")
print(pnl_path)

Saved signal panel:
/content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/data/processed/v2_01_signal_prices.parquet

Saved prototype P&L panel:
/content/drive/MyDrive/Colab Notebooks/SuperbCommand/Multi-Asset CTA Strategy v2/v2.01/data/processed/v2_01_pnl_prices_prototype.parquet

# V2.01 completion gate

Expected outputs:

- `v2.01/config/v2_01_config.json`
- `v2.01/manifests/v2_master_universe.csv`
- `v2.01/manifests/v2_01_prototype_coverage.csv`
- `v2.01/manifests/v2_01_signal_quality.csv`
- `v2.01/data/processed/v2_01_signal_prices.parquet`
- `v2.01/data/processed/v2_01_pnl_prices_prototype.parquet`

Before notebook 02, review markets that require stronger data sources, particularly European/UK/Japanese rates and several industrial commodities.

## Research Outcome

Book 01 established the data architecture for the Multi-Asset CTA Strategy V2 research programme. A broad cross-asset universe was successfully assembled across equity indices, FX, commodities, bonds/rates and Bitcoin, while explicitly separating **signal series** from **economic P&L series** where the two are not equivalent.

The resulting framework recognises that price indices, spot FX and continuous futures are suitable research inputs for signal construction but do not necessarily represent complete investable returns because of dividends, interest-rate carry, collateral returns and futures roll effects. This distinction is preserved for later portfolio implementation rather than implicitly treating all downloaded price histories as total-return assets.

The final research universe contains 53 usable markets spanning:

- 18 equity indices / equity-market state series;
- 17 commodities;
- 10 FX markets;
- 7 bonds/rates markets;
- 1 digital asset (BTC-USD).

Individual equities were excluded from the present V2 research universe. Bitcoin was retained as a separate `DIGITAL_ASSETS` asset class, with 1 January 2017 used as its formal research admission date while earlier observations are retained solely for indicator warm-up.

A further methodological principle established in Book 01 is the distinction between **available historical data** and **formally admissible research observations**. Pre-research history may be used to warm long-horizon indicators without allowing those observations to enter subsequent event statistics or model evaluation.

### Conclusion

Book 01 provides a reproducible, cross-asset data foundation for the transition-strategy research programme. Its principal contribution is architectural rather than predictive: it creates a common research panel while preserving the economic distinctions required for later conversion from signal research into an investable CTA portfolio.

**Status: FROZEN as the V2 universe and prototype data-engine foundation.**